### ISSUE TITLE
Two test failures in french phonemizer sqlite3 connection

### ISSUE THREAD

**Issue by mweinelt** [rhasspy/gruut#10]
Not entirely sure what db_path it's trying to access here, and these are the only two tests failing for me.

```pytb
======================================================================
ERROR: test_last_token (tests.test_fr_phonemizer.FrenchPhonemizerTestCase)
Ensure liason does not leave last token
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/test_fr_phonemizer.py", line 75, in test_last_token
    phonemes = text_to_phonemes("Est-ce-que", lang="fr")
  File "/build/source/gruut/__init__.py", line 224, in text_to_phonemes
    return_tuples.extend(
  File "/build/source/gruut/__init__.py", line 224, in <genexpr>
    return_tuples.extend(
  File "/build/source/gruut/lang.py", line 858, in phonemize
    for (token1, token1_pron), (token2, token2_pron) in pairwise(
  File "/build/source/gruut/utils.py", line 125, in pairwise
    next(b, None)
  File "/build/source/gruut/phonemize.py", line 271, in phonemize
    token_pron = self.get_pronunciation(token)
  File "/build/source/gruut/phonemize.py", line 328, in get_pronunciation
    word_prons = list(pron for _word, pron in self.select_prons(word))
  File "/build/source/gruut/phonemize.py", line 328, in <genexpr>
    word_prons = list(pron for _word, pron in self.select_prons(word))
  File "/build/source/gruut/phonemize.py", line 607, in select_prons
    self._connect()
  File "/build/source/gruut/phonemize.py", line 481, in _connect
    self.db_conn = sqlite3.connect(self.db_path)
sqlite3.OperationalError: unable to open database file

======================================================================
ERROR: test_liason (tests.test_fr_phonemizer.FrenchPhonemizerTestCase)
Test addition of liason
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/test_fr_phonemizer.py", line 51, in test_liason
    sentence = self._without_and_with_liason(
  File "/build/source/tests/test_fr_phonemizer.py", line 93, in _without_and_with_liason
    phonemes_no_liason = list(phonemizer_no_liason.phonemize(sentence.tokens))
  File "/build/source/gruut/lang.py", line 849, in phonemize
    yield from token_phonemes
  File "/build/source/gruut/phonemize.py", line 271, in phonemize
    token_pron = self.get_pronunciation(token)
  File "/build/source/gruut/phonemize.py", line 328, in get_pronunciation
    word_prons = list(pron for _word, pron in self.select_prons(word))
  File "/build/source/gruut/phonemize.py", line 328, in <genexpr>
    word_prons = list(pron for _word, pron in self.select_prons(word))
  File "/build/source/gruut/phonemize.py", line 607, in select_prons
    self._connect()
  File "/build/source/gruut/phonemize.py", line 481, in _connect
    self.db_conn = sqlite3.connect(self.db_path)
sqlite3.OperationalError: unable to open database file

----------------------------------------------------------------------
```

I tried to debug this by printing out the db_path and it is only opening `:memory:` and `gruut/data/en-us/lexicon.db`.

```diff
diff --git a/gruut/phonemize.py b/gruut/phonemize.py
index 4650fd3..934af86 100644
--- a/gruut/phonemize.py
+++ b/gruut/phonemize.py
@@ -477,8 +477,13 @@ class SqlitePhonemizer(Phonemizer):
         if self.db_conn is None:
             assert self.db_path is not None, "No sqlite3 database path"
 
-            _LOGGER.debug("Connecting to %s", self.db_path)
+            _LOGGER.error("Connecting to %s", self.db_path)
             self.db_conn = sqlite3.connect(self.db_path)
+            _LOGGER.error("OK")
+
+            import sys
+            sys.stdout.flush()
+            sys.stderr.flush()
 
             if not self.feature_to_id:
                 # Try to load feature names from the database
```

**Comment by mweinelt** [comment]
Oddly, there are more failing tests with regard to gruut when building the tests for tts 0.1.2.

> DEBUG    gruut.phonemize:phonemize.py:480 Connecting to /nix/store/lgiasx76vy73z6r2hq6rbmmwp3620qvi-python3.8-gruut-1.2.0/lib/python3.8/site-packages/gruut/data/en-us/espeak/lexicon.db

But the espeak directory does not exist. There is a `lexicon.db` in the directory above.

```
❯ find /nix/store/lgiasx76vy73z6r2hq6rbmmwp3620qvi-python3.8-gruut-1.2.0/lib/python3.8/site-packages/gruut/data/
/nix/store/lgiasx76vy73z6r2hq6rbmmwp3620qvi-python3.8-gruut-1.2.0/lib/python3.8/site-packages/gruut/data/
/nix/store/lgiasx76vy73z6r2hq6rbmmwp3620qvi-python3.8-gruut-1.2.0/lib/python3.8/site-packages/gruut/data/en-us
/nix/store/lgiasx76vy73z6r2hq6rbmmwp3620qvi-python3.8-gruut-1.2.0/lib/python3.8/site-packages/gruut/data/en-us/g2p
/nix/store/lgiasx76vy73z6r2hq6rbmmwp3620qvi-python3.8-gruut-1.2.0/lib/python3.8/site-packages/gruut/data/en-us/g2p/model.crf
/nix/store/lgiasx76vy73z6r2hq6rbmmwp3620qvi-python3.8-gruut-1.2.0/lib/python3.8/site-packages/gruut/data/en-us/pos
/nix/store/lgiasx76vy73z6r2hq6rbmmwp3620qvi-python3.8-gruut-1.2.0/lib/python3.8/site-packages/gruut/data/en-us/pos/model.crf
/nix/store/lgiasx76vy73z6r2hq6rbmmwp3620qvi-python3.8-gruut-1.2.0/lib/python3.8/site-packages/gruut/data/en-us/lexicon.db
```

**Comment by synesthesiam** [comment]
I forgot to include the espeak `lexicon.db` file for English in gruut 1.2.0. Please upgrade to 1.2.2 and try again.

Regarding the French test failures, you will need to `pip install gruut-lang-fr` first. Sorry, this was not mentioned anywhere in the docs.

**Comment by mweinelt** [comment]
> I forgot to include the espeak lexicon.db file for English in gruut 1.2.0. Please upgrade to 1.2.2 and try again.

Indeed, that fixes the TTS test failures. 

There does not seem to be a tag for versions 1.2.1 and 1.2.2, those versions are only up on PyPi.
 
> Regarding the French test failures, you will need to pip install gruut-lang-fr first. Sorry, this was not mentioned anywhere in the docs.

The way we package them up means that gruut has all its language-specific packages accessible via its `PYTHONPATH`, but other than that they're all in their individual site-packages directory and are only linked together via that environment variable. 

I probably have to read up on how it finds paths to the language packs.

**Comment by mweinelt** [comment]
Ah, it seems my language files packaging is at fault.

```
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr/__pycache__
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr/__pycache__/__init__.cpython-38.pyc
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr/VERSION
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr/__init__.py
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr-1.2.dist-info
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr-1.2.dist-info/INSTALLER
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr-1.2.dist-info/METADATA
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr-1.2.dist-info/RECORD
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr-1.2.dist-info/REQUESTED
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr-1.2.dist-info/WHEEL
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr-1.2.dist-info/direct_url.json
/nix/store/fih6hsnikzc4pmb6ri6nri58jghacz7z-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages/gruut_lang_fr-1.2.dist-info/top_level.txt
```

**Comment by synesthesiam** [comment]
The code for locating language files is here if you're interested: https://github.com/rhasspy/gruut/blob/6590a671fa4fea914f3bdd0a9e17e57e68309298/gruut/utils.py#L17

**Comment by mweinelt** [comment]
Locating the packages works, just the data files given in the setup.py are nowhere to be found.

https://github.com/rhasspy/gruut/blob/6590a671fa4fea914f3bdd0a9e17e57e68309298/gruut-lang-fr/setup.py#L26-L35

```
❯ cd gruut-lang-fr
❯ fd
LANGUAGE
gruut_lang_fr
gruut_lang_fr/VERSION
gruut_lang_fr/__init__.py
gruut_lang_fr/pos
gruut_lang_fr/pos/results.txt
setup.py
```

**Comment by mweinelt** [comment]
Sorry, I don't want to bother you too much.

The package_data referenced in the language packages are not part of the repository, but part of the pypi sdist. Can you add them to the repository?

**Comment by synesthesiam** [comment]
Please keep bothering me :slightly_smiling_face: 

The problem here is that the `lexicon.db` files for some languages are over the size limit that GitHub has for files stored in a repo. So I either need to use GitLFS or assume that the files can be pulled from a release.

Any suggestions?

**Comment by mweinelt** [comment]
With my package maintainer hat on: We would be fine with fetching via git-lfs, and it is probably easier to work with, than having to track/manage separate release artifacts.

**Comment by synesthesiam** [comment]
I've pushed the files up to a side branch: https://github.com/rhasspy/gruut/tree/v1.2

Turns the biggest file was still under the limit!

**Comment by mweinelt** [comment]
Awesome, finally a non-packaging issue! :grinning: 

```
======================================================================
FAIL: test_liason (tests.test_fr_phonemizer.FrenchPhonemizerTestCase)
Test addition of liason
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/test_fr_phonemizer.py", line 51, in test_liason
    sentence = self._without_and_with_liason(
  File "/build/source/tests/test_fr_phonemizer.py", line 104, in _without_and_with_liason
    self.assertEqual(word_phonemes, with_phonemes)
AssertionError: Lists differ: ['l', 'e'] != ['l', 'e', 'z']

Second list contains 1 additional elements.
First extra element 2:
'z'

- ['l', 'e']
+ ['l', 'e', 'z']
?          +++++


----------------------------------------------------------------------
Ran 44 tests in 1.516s

FAILED (failures=1)
```

**Comment by synesthesiam** [comment]
The PYTHONPATH needs to be augmented if you don't install the gruut_lang_* modules. See [this example in run-tests.sh](https://github.com/rhasspy/gruut/blob/6e261552db2f18f7cdac9391618d3b0b29e19b99/scripts/run-tests.sh#L17). The liason test is failing because it can't locate the French part of speech model.

I'm not a French speaker, but as I understand it, liason in French is the addition of "blending sounds" between certain words. The [rules can get quite complex](https://github.com/juliacarbajal/french_phonologizer/blob/master/phonologize.py), so I've only implemented a few of them. But they depend on part of speech tagging, which is why they need the POS model.

**Comment by mweinelt** [comment]
> The PYTHONPATH needs to be augmented if you don't install the gruut_lang_* modules. See this example in run-tests.sh. The liason test is failing because it can't locate the French part of speech model.

The PYTHONPATH looks pretty good, I introduced newlines after each `:` to improve readability.

```
/nix/store/8n4mdbzwklnmvf9z6ydr30jrnwc6mpcz-python3.8-gruut-1.2.2/lib/python3.8/site-packages:
/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/site-packages:
/nix/store/5yfmn9py4bjn5hqzrz6qpbbc3l07d697-python3.8-setuptools-54.2.0/lib/python3.8/site-packages:
/nix/store/vq4cs34z21hbri21pq5l5avc7qdw54rx-python3.8-wheel-0.36.2/lib/python3.8/site-packages:
/nix/store/xzgkgip067x7zxlrkfaj6nbasl7k4l46-python3.8-pip-21.0.1/lib/python3.8/site-packages:
/nix/store/m1xzfbib6f5ci9yrjny3p7xfdw21gzlp-python3.8-Babel-2.9.1/lib/python3.8/site-packages:
/nix/store/8q8qxp9gcmrdby0hnkybkbc6yyhxpiwg-python3.8-pytz-2021.1/lib/python3.8/site-packages:
/nix/store/fkjwqvsghaj2as0n46v773y3gj0nknxx-python3.8-gruut-ipa-0.9.2/lib/python3.8/site-packages:
/nix/store/p0jn1g0gkz8n5vd2a1vd3lia0xd3vclf-python3.8-jsonlines-1.2.0/lib/python3.8/site-packages:
/nix/store/hllx5h4hsrk6v0lcgnvibg7vfi5xkxmb-python3.8-six-1.16.0/lib/python3.8/site-packages:
/nix/store/azk4ycpllqz6yzwpwazlzldkdvh5bmij-python3.8-num2words-0.5.10/lib/python3.8/site-packages:
/nix/store/09nswns2axpcaqq8gm4slk0dv76sj21n-python3.8-docopt-0.6.2/lib/python3.8/site-packages:
/nix/store/lbzvq16abvw2sa0iyld9lxm79psmmrsp-python3.8-python-crfsuite-0.9.7/lib/python3.8/site-packages:
/nix/store/wi47akarfaq9isjsqnzk7j7h0r01ajhj-python3.8-gruut-lang-cs-1.2.2/lib/python3.8/site-packages:
/nix/store/9lb84rdf2dfdz42vll1a0vy9k8i18q3w-python3.8-gruut-lang-de-1.2.2/lib/python3.8/site-packages:
/nix/store/p0s2abvlrp6nrj1zwn6nrpkwx2a9b3g0-python3.8-gruut-lang-es-1.2.2/lib/python3.8/site-packages:
/nix/store/hkzjvzjngjn81qxjczlcf9rq2na7bp30-python3.8-gruut-lang-fr-1.2.2/lib/python3.8/site-packages:
/nix/store/q5dvx0jrvy4xkyzpp1azc4rb8za5yyzd-python3.8-gruut-lang-it-1.2.2/lib/python3.8/site-packages:
/nix/store/5458ncn0c9r9if0s7zxpm6b89znpk0sz-python3.8-gruut-lang-nl-1.2.2/lib/python3.8/site-packages:
/nix/store/bc66a637skc1j07wv3qbirhhc1xj0bw4-python3.8-gruut-lang-pt-1.2.2/lib/python3.8/site-packages:
/nix/store/5qikp9816449i7a7m1zhcxv8zcs5lcni-python3.8-gruut-lang-ru-1.2.2/lib/python3.8/site-packages:
/nix/store/9bzx7algn8scp45nflqbqa1xxwphc1ck-python3.8-gruut-lang-sv-1.2.2/lib/python3.8/site-packages:
/nix/store/i9514df0cphjbkrb86xmb2ps3a93mcm8-python3.8-gruut-lang-sw-1.2.2/lib/python3.8/site-packages
```

> I'm not a French speaker, but as I understand it, liason in French is the addition of "blending sounds" between certain words. The rules can get quite complex, so I've only implemented a few of them. But they depend on part of speech tagging, which is why they need the POS model.

Pretty sure you are talking about a liaison, like how the article and the word following it connect which each other. See https://github.com/juliacarbajal/french_phonologizer/blob/master/phonologize.py#L87.

**Comment by synesthesiam** [comment]
Lol, I missed the extra "i" in lia**i**son this whole time :man_facepalming:

**Comment by mweinelt** [comment]
The POS model files are not part of the package_data! :smile: 

https://github.com/rhasspy/gruut/blob/6e261552db2f18f7cdac9391618d3b0b29e19b99/gruut-lang-fr/setup.py#L28-L35

**Comment by synesthesiam** [comment]
I might wear out the facepalm emoji here :man_facepalming: 

OK, got the POS model added to the French model. I can at least confirm that tests pass for me with a clean pull of v1.2 after running the `create-venv.sh` script.

Thanks for your patience :+1:

**Comment by mweinelt** [comment]
Exciting. Things are falling into place. All that is left now is the kind ask for a git tag to build from, as opposed to a random commit. Would that be possible?

Happy to be your rubber duck! :duck:

**Comment by synesthesiam** [comment]
Sure! I've moved the [`v1.2.0` tag](https://github.com/rhasspy/gruut/releases/tag/v1.2.0) to this most recent commit. Will that work?

**Comment by mweinelt** [comment]
Yep, that works! Thank you.
