### ISSUE TITLE
Can't install Gruut

### ISSUE THREAD

**Issue by Ciclarion** [rhasspy/gruut#12]
Hello,

I'm trying to install Gruut, either through 

> pip install gruut

or by downloading this repo and installing directly from it. However, i'm encoutering this bug each time : 

```
ERROR: Command errored out with exit status 1:
     command: 'c:\users\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AppData\\Local\\Temp\\pip-install-w1co1jh7\\gruut_52ebc4610a16462db0ca35f7948a04df\\setup.py'"'"'; __file__='"'"'C:\\Users\\AppData\\Local\\Temp\\pip-install-w1co1jh7\\gruut_52ebc4610a16462db0ca35f7948a04df\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\AppData\Local\Temp\pip-pip-egg-info-o9nvwlt0'
         cwd: C:\Users\AppData\Local\Temp\pip-install-w1co1jh7\gruut_52ebc4610a16462db0ca35f7948a04df\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AppData\Local\Temp\pip-install-w1co1jh7\gruut_52ebc4610a16462db0ca35f7948a04df\setup.py", line 17, in <module>
        long_description = readme_path.read_text()
      File "c:\users\appdata\local\programs\python\python39\lib\pathlib.py", line 1257, in read_text
        return f.read()
      File "c:\users\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 3521: character maps to <undefined>
```

I'm on Windows 10 with python 3.9.5.

**Comment by Ciclarion** [comment]
The fix proposed [here](https://github.com/rhasspy/gruut/pull/11) seems to work, so i closed the issue.
